# Generated by Django 6.0.1 on 2026-01-27 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Условие задачи')),
                ('subject', models.CharField(choices=[('Информатика', 'Информатика'), ('Математика', 'Математика'), ('Физика', 'Физика')], max_length=50, verbose_name='Предмет')),
                ('topic', models.CharField(max_length=100, verbose_name='Тема')),
                ('difficulty', models.IntegerField(default=1, verbose_name='Сложность (1-10)')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Правильный ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('room_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1000, verbose_name='Рейтинг Elo')),
                ('tasks_solved', models.IntegerField(default=0, verbose_name='Решено задач')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Всего попыток')),
                ('math_solved', models.IntegerField(default=0, verbose_name='Решено (Математика)')),
                ('inf_solved', models.IntegerField(default=0, verbose_name='Решено (Информатика)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
