# Generated by Django 6.0.1 on 2026-02-02 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_timer_enabled_alter_match_winner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
        migrations.RemoveField(
            model_name='match',
            name='task',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subject',
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.CharField(default='Средний', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timer_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.CharField(max_length=200),
        ),
    ]
