# Generated by Django 6.0.1 on 2026-02-02 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_match_task_alter_match_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timer_enabled',
        ),
        migrations.AddField(
            model_name='profile',
            name='active_days_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='tasks_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_solve_time',
            field=models.FloatField(default=0),
        ),
    ]
