# Generated by Django 6.0.1 on 2026-02-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_profile_time_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='timer_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
