# Generated by Django 6.0.1 on 2026-02-04 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_time_limit_profile_timer_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active_days_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_active_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tasks_attempted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tasks_solved',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_solve_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='answer',
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='time_limit',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
