# Generated by Django 6.0.1 on 2026-02-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_profile_active_days_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='time_limit',
            field=models.IntegerField(default=15),
        ),
    ]
