# Generated by Django 6.0.1 on 2026-02-04 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_room_difficulty_room_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='points',
        ),
        migrations.AddField(
            model_name='room',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='correct_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='difficulty',
            field=models.CharField(default='easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
