# Generated by Django 6.0.1 on 2026-02-05 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_room_difficulty_alter_room_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='room',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='room',
            name='task',
        ),
        migrations.RemoveField(
            model_name='room',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Default Room', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(related_name='joined_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(max_length=100),
        ),
    ]
