# Generated by Django 6.0.1 on 2026-02-05 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_room_difficulty_remove_room_opponent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='players',
        ),
        migrations.AddField(
            model_name='room',
            name='difficulty',
            field=models.CharField(default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='Битва', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], default='easy', max_length=20),
        ),
    ]
