# Generated by Django 6.0.1 on 2026-02-05 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_room_difficulty_remove_room_name_room_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
    ]
