# Generated by Django 6.0.1 on 2026-02-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_room_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='time_limit',
            field=models.IntegerField(default=60),
        ),
    ]
