# Generated by Django 6.0.1 on 2026-02-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_room_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='time_limit',
            field=models.IntegerField(default=300),
        ),
    ]
