# Generated by Django 6.0.1 on 2026-02-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_solution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(choices=[('math', 'Математика'), ('inf', 'Информатика'), ('phys', 'Физика')], default='math', max_length=20, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(max_length=100, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], default='easy', max_length=20, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
