# Generated by Django 6.0.1 on 2026-02-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_task_options_task_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_time',
            field=models.IntegerField(default=600),
        ),
    ]
