# Generated by Django 6.0.1 on 2026-02-05 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_profile_preferred_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tasks_attempted',
            field=models.IntegerField(default=0, verbose_name='Всего попыток'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_solved_time',
            field=models.IntegerField(default=0, verbose_name='Всего секунд затрачено'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_time',
            field=models.IntegerField(default=600, verbose_name='Время по умолчанию (сек)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=1000, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Верно'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solved_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата решения'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='core.task'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
