# Generated by Django 6.0.1 on 2026-02-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_profile_tasks_attempted_profile_total_solved_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tasks_solved',
            field=models.IntegerField(default=0, verbose_name='Уникальных задач решено'),
        ),
    ]
