# Generated by Django 6.0.1 on 2026-02-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_profile_tasks_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='subject',
            field=models.CharField(choices=[('math', 'Математика'), ('inf', 'Информатика'), ('phys', 'Физика')], default='math', max_length=20, verbose_name='Предмет дуэли'),
        ),
    ]
